from snakemake.utils import min_version
min_version('7.0')
import os
cwd = os.getcwd()
print(cwd)

# Include base environment and tools that are required for Snakefile script (e.g., Pandas)
conda: "envs/global_env.yaml"
# Import config file so all included scripts have access to config data
configfile: "config/config.yaml"

include: "rules/commons.smk"
include: "rules/process.smk"

rule all:
    input: 
        expand("results/cat/hybrid_ref_tx.fa.gz", id=samples['sample_id']),
        expand("results/gtf/hybrid.gtf.gz", id=samples['sample_id']),
        expand("results/salmon_idx/info.json", id=samples['sample_id']),
        expand("results/qc/{id}_fastqc.done", id=sample_reads['sample_id']),
        expand("results/salmon/{id}/quant.sf", id=sample_reads['sample_id']),
        expand("results/salmon/{id}/quant.sf", id=sample_reads['sample_id']),
        expand("results/star/{id}.sorted.bam", id=sample_reads['sample_id']),
        expand("results/report/{id}.html", id=sample_reads['sample_id']),
