samples: config/samples.tsv
units: config/units.tsv
ref_fa: /home/ref/hg/GRCh38.primary_assembly.genome.fa.gz
ref_gtf: /home/ref/hg/gencode.v47.primary_assembly.annotation.gtf.gz
ref_tx: /home/ref/hg/gencode.v47.transcripts.fa.gz